[tool.black]
line-length = 88
target-version = ["py311", "py312"]
exclude = '''
/(
    \.venv
  | venv
  | build
  | dist
  | migrations
)/
'''

[tool.isort]
profile = "black"
line_length = 88
src_paths = ["backend"]
