# Generated by Django 5.0.7 on 2025-11-08 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_alter_payment_resident"),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("certificado", "Certificados"),
                            ("reglamento", "Reglamentos"),
                            ("formulario", "Formularios"),
                            ("otro", "Otros"),
                        ],
                        default="otro",
                        max_length=30,
                    ),
                ),
                ("archivo", models.FileField(upload_to="documentos/")),
                ("publico", models.BooleanField(default=True)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-creado_en"],
            },
        ),
    ]
