# Generated by Django 5.0.7 on 2025-11-08 20:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_document"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="document",
            options={"ordering": ("-created_at",)},
        ),
        migrations.RenameField(
            model_name="document",
            old_name="creado_en",
            new_name="created_at",
        ),
        migrations.RemoveField(
            model_name="document",
            name="archivo",
        ),
        migrations.RemoveField(
            model_name="document",
            name="categoria",
        ),
        migrations.RemoveField(
            model_name="document",
            name="publico",
        ),
        migrations.RemoveField(
            model_name="document",
            name="titulo",
        ),
        migrations.AddField(
            model_name="document",
            name="file",
            field=models.FileField(default="", upload_to="documents/"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="document",
            name="is_public",
            field=models.BooleanField(default=True, verbose_name="Público"),
        ),
        migrations.AddField(
            model_name="document",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="documents",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="title",
            field=models.CharField(default="", max_length=150, verbose_name="Título"),
            preserve_default=False,
        ),
    ]
