# Generated by Django 5.0.7 on 2025-11-09 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_alter_document_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="document",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Documento",
                "verbose_name_plural": "Documentos",
            },
        ),
        migrations.RemoveField(
            model_name="document",
            name="file",
        ),
        migrations.RemoveField(
            model_name="document",
            name="owner",
        ),
        migrations.RemoveField(
            model_name="document",
            name="title",
        ),
        migrations.AddField(
            model_name="document",
            name="archivo",
            field=models.FileField(default="", upload_to="documentos/%Y/%m/"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="document",
            name="categoria",
            field=models.CharField(
                choices=[
                    ("certificado", "Certificado"),
                    ("reglamento", "Reglamento"),
                    ("formulario", "Formulario"),
                    ("otro", "Otro"),
                ],
                default="otro",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="titulo",
            field=models.CharField(default="", max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="document",
            name="is_public",
            field=models.BooleanField(default=True),
        ),
    ]
