# Generated by Django 5.0.7 on 2025-11-09 23:45

import core.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_alter_document_options_remove_document_file_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, unique=True)),
                ("descripcion", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Categoría de documento",
                "verbose_name_plural": "Categorías de documentos",
                "ordering": ["nombre"],
            },
        ),
        migrations.RemoveField(
            model_name="document",
            name="is_public",
        ),
        migrations.AddField(
            model_name="document",
            name="descripcion",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="document",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="document",
            name="subido_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="documentos_subidos",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="document",
            name="visibilidad",
            field=models.CharField(
                choices=[
                    ("PUBLICO", "Público"),
                    ("RESIDENTES", "Sólo residentes"),
                    ("STAFF", "Sólo staff (Admin/Secretario)"),
                ],
                default="RESIDENTES",
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="archivo",
            field=models.FileField(
                upload_to=core.models.document_upload_to,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        [
                            "pdf",
                            "doc",
                            "docx",
                            "xls",
                            "xlsx",
                            "csv",
                            "ppt",
                            "pptx",
                            "jpg",
                            "jpeg",
                            "png",
                        ]
                    ),
                    core.models.validate_file_size,
                ],
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="categoria",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="documentos",
                to="core.documentcategory",
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["is_active"], name="core_docume_is_acti_7ca999_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["visibilidad"], name="core_docume_visibil_95e48e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["created_at"], name="core_docume_created_f1aada_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="document",
            constraint=models.CheckConstraint(
                check=models.Q(("titulo__regex", ".*\\S.*")),
                name="document_title_not_blank",
            ),
        ),
    ]
