# Generated by Django 5.0.7 on 2025-11-10 20:57

import core.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_documentcategory_remove_document_is_public_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="IncidentCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, unique=True)),
                ("descripcion", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Categoría de incidencia",
                "verbose_name_plural": "Categorías de incidencias",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Incident",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("descripcion", models.TextField()),
                (
                    "foto",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=core.models.incident_upload_to,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["jpg", "jpeg", "png"]
                            ),
                            core.models.validate_image_size,
                        ],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Abierta"),
                            ("IN_PROGRESS", "En progreso"),
                            ("RESOLVED", "Resuelta"),
                            ("REJECTED", "Rechazada"),
                        ],
                        default="OPEN",
                        max_length=20,
                    ),
                ),
                ("nota_resolucion", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "asignada_a",
                    models.ForeignKey(
                        blank=True,
                        help_text="(Opcional) Miembro del staff que gestionará la incidencia",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="incidencias_asignadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reportado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incidencias_reportadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "categoria",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="incidencias",
                        to="core.incidentcategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Incidencia",
                "verbose_name_plural": "Incidencias",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status"], name="core_incide_status_cb96ff_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="core_incide_created_f536cb_idx"
                    ),
                ],
            },
        ),
    ]
