# Generated by Django 5.0.7 on 2025-11-10 21:52

import core.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_resourcecategory_alter_incident_foto_resource_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="incident",
            name="foto",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=core.models.incident_upload_to,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["jpg", "jpeg", "png"]
                    ),
                    core.models.validate_image_size,
                ],
            ),
        ),
    ]
