# Generated by Django 5.0.7 on 2025-11-13 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_alter_incident_foto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pendiente"),
                    ("paid", "Pagado"),
                    ("cancelled", "Cancelado"),
                ],
                default="pending",
                max_length=10,
                verbose_name="Estado",
            ),
        ),
    ]
