# Generated by Django 5.0.7 on 2025-11-13 19:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_alter_payment_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="payment",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Pago",
                "verbose_name_plural": "Pagos",
            },
        ),
        migrations.RemoveConstraint(
            model_name="payment",
            name="uniq_paid_per_resident_fee",
        ),
        migrations.AddField(
            model_name="payment",
            name="origin",
            field=models.CharField(
                choices=[("fee", "Cuota"), ("reservation", "Reserva")],
                default="reservation",
                max_length=20,
                verbose_name="Origen",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="reservation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payments",
                to="core.reservation",
                verbose_name="Reserva",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Creado en"),
        ),
        migrations.AlterField(
            model_name="payment",
            name="fee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payments",
                to="core.fee",
                verbose_name="Cuota",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="resident",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Residente",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pendiente"),
                    ("paid", "Pagado"),
                    ("cancelled", "Cancelado"),
                ],
                default="pending",
                max_length=20,
                verbose_name="Estado",
            ),
        ),
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("origin", "fee")),
                fields=("resident", "fee", "origin"),
                name="unique_fee_payment_per_resident",
            ),
        ),
    ]
