# Generated by Django 5.0.7 on 2025-11-13 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_alter_payment_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="resource",
            name="precio_por_hora",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Dejar en blanco o 0 para recursos gratuitos (ej. salón de eventos).",
                max_digits=9,
                null=True,
                verbose_name="Precio por hora",
            ),
        ),
    ]
