# Generated by Django 5.0.7 on 2025-11-14 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_resource_precio_por_hora"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="fee",
            options={"verbose_name": "Deuda", "verbose_name_plural": "Deudas"},
        ),
        migrations.AlterField(
            model_name="fee",
            name="amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Monto sugerido",
            ),
        ),
        migrations.AlterField(
            model_name="fee",
            name="period",
            field=models.CharField(
                help_text="Ej: Cancha fútbol 1, Cancha básquet 2, Cancha pádel 1, etc.",
                max_length=100,
                verbose_name="Nombre de deuda",
            ),
        ),
    ]
