# Generated by Django 5.0.7 on 2025-11-14 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_alter_fee_options_alter_fee_amount_alter_fee_period"),
    ]

    operations = [
        migrations.AddField(
            model_name="inscriptionevidence",
            name="email",
            field=models.EmailField(
                blank=True,
                help_text="Usaremos este correo para avisarte si tu inscripción fue aprobada o rechazada.",
                max_length=254,
                null=True,
                verbose_name="Correo de contacto",
            ),
        ),
    ]
