# Generated by Django 5.0.7 on 2025-11-14 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_inscriptionevidence_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="inscriptionevidence",
            name="address",
            field=models.CharField(
                blank=True,
                help_text="Dirección del domicilio asociado a la inscripción.",
                max_length=255,
                verbose_name="Dirección",
            ),
        ),
        migrations.AddField(
            model_name="inscriptionevidence",
            name="full_name",
            field=models.CharField(
                blank=True,
                help_text="Nombre de la persona que solicita unirse a la Junta de Vecinos.",
                max_length=150,
                verbose_name="Nombre completo",
            ),
        ),
    ]
