# Generated by Django 5.0.7 on 2025-11-14 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0023_inscriptionevidence_address_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inscriptionevidence",
            name="address",
        ),
        migrations.RemoveField(
            model_name="inscriptionevidence",
            name="full_name",
        ),
        migrations.AddField(
            model_name="inscriptionevidence",
            name="applicant_address",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Dirección"
            ),
        ),
        migrations.AddField(
            model_name="inscriptionevidence",
            name="applicant_name",
            field=models.CharField(
                blank=True,
                max_length=150,
                null=True,
                verbose_name="Nombre del solicitante",
            ),
        ),
    ]
