# Generated by Django 5.0.7 on 2025-11-15 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0024_remove_inscriptionevidence_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="receipt_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="payment_receipts/",
                verbose_name="Comprobante de transferencia",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="receipt_note",
            field=models.TextField(blank=True, verbose_name="Nota del vecino"),
        ),
        migrations.AddField(
            model_name="payment",
            name="receipt_uploaded_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Comprobante subido el"
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="staff_note",
            field=models.TextField(blank=True, verbose_name="Nota interna"),
        ),
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pendiente"),
                    ("pending_review", "Pendiente de revisión"),
                    ("paid", "Pagado"),
                    ("cancelled", "Cancelado"),
                ],
                default="pending",
                max_length=20,
                verbose_name="Estado",
            ),
        ),
    ]
