# Generated by Django 5.0.7 on 2025-11-15 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0025_payment_receipt_file_payment_receipt_note_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="review_note",
            field=models.TextField(
                blank=True,
                help_text="Motivo o comentario para el vecino (si el pago sigue pendiente).",
                null=True,
                verbose_name="Comentario de revisión",
            ),
        ),
    ]
