# Generated by Django 5.0.7 on 2025-11-15 02:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0026_payment_review_note"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="staff_note",
        ),
        migrations.AddField(
            model_name="payment",
            name="reviewed_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Revisado en"
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payments_reviewed",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Revisado por",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="receipt_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="payment_receipts/",
                verbose_name="Comprobante",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="receipt_note",
            field=models.TextField(
                blank=True, null=True, verbose_name="Nota del vecino sobre el pago"
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="receipt_uploaded_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Comprobante subido en"
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="review_note",
            field=models.TextField(
                blank=True, null=True, verbose_name="Comentario para el vecino"
            ),
        ),
    ]
