# Generated by Django 5.0.7 on 2025-11-15 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0027_remove_payment_staff_note_payment_reviewed_at_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="payment",
            old_name="review_note",
            new_name="review_comment",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="receipt_note",
        ),
    ]
