# Generated by Django 5.0.7 on 2025-11-15 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0028_rename_review_note_payment_review_comment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="announcement",
            name="importante",
            field=models.BooleanField(
                default=False,
                help_text="Si está activo, este aviso se destacará para los vecinos.",
                verbose_name="Marcar como importante",
            ),
        ),
    ]
