# Generated by Django 5.0.7 on 2025-11-15 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0029_announcement_importante"),
    ]

    operations = [
        migrations.RenameField(
            model_name="inscriptionevidence",
            old_name="applicant_address",
            new_name="address",
        ),
        migrations.RemoveField(
            model_name="inscriptionevidence",
            name="applicant_name",
        ),
        migrations.AddField(
            model_name="inscriptionevidence",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Nombre"
            ),
        ),
        migrations.AddField(
            model_name="inscriptionevidence",
            name="last_name",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Apellido"
            ),
        ),
        migrations.AddField(
            model_name="inscriptionevidence",
            name="rut",
            field=models.CharField(
                blank=True,
                help_text="Ingresa tu RUT con o sin puntos, incluyendo el dígito verificador.",
                max_length=12,
                null=True,
                verbose_name="RUT",
            ),
        ),
        migrations.AddField(
            model_name="resident",
            name="rut",
            field=models.CharField(
                blank=True, max_length=12, null=True, unique=True, verbose_name="RUT"
            ),
        ),
    ]
