# Generated by Django 5.0.7 on 2025-11-15 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0030_rename_applicant_address_inscriptionevidence_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="inscriptionevidence",
            name="desired_role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("VECINO", "Vecino"),
                    ("DELEGADO", "Delegado"),
                    ("TESORERO", "Tesorero"),
                    ("SECRETARIO", "Secretario"),
                    ("PRESIDENTE", "Presidente"),
                ],
                max_length=20,
                null=True,
                verbose_name="Rol solicitado",
            ),
        ),
    ]
