# Generated by Django 5.0.7 on 2025-11-20 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0031_inscriptionevidence_desired_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="cancel_reason",
            field=models.TextField(
                blank=True,
                help_text="Motivo indicado por el vecino al cancelar la reserva.",
                null=True,
                verbose_name="Motivo de cancelación",
            ),
        ),
    ]
