# Generated by Django 5.0.7 on 2025-11-21 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0033_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="is_important",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[
                    ("announcement", "Aviso"),
                    ("incident", "Incidencia"),
                    ("meeting", "Reunión"),
                    ("payment_review", "Pago pendiente"),
                ],
                default="announcement",
                max_length=50,
            ),
        ),
    ]
