# Generated by Django 5.0.7 on 2025-11-22 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0034_notification_is_important_alter_notification_type"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="notification",
            options={"ordering": ["-is_important", "-created_at"]},
        ),
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[
                    ("announcement", "Aviso"),
                    ("incident", "Incidencia"),
                    ("meeting", "Reunión"),
                    ("payment", "Pago"),
                    ("subscription", "Inscripción"),
                ],
                max_length=20,
            ),
        ),
    ]
