# Generated by Django 5.0.7 on 2025-11-30 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0036_meeting_creado_por"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inscriptionevidence",
            name="note",
            field=models.TextField(blank=True, verbose_name="Nota"),
        ),
        migrations.AlterField(
            model_name="inscriptionevidence",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pendiente"),
                    ("APPROVED", "Aprobada"),
                    ("REJECTED", "Rechazada"),
                ],
                default="PENDING",
                max_length=10,
                verbose_name="Estado",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pendiente"),
                    ("pending_review", "Pendiente de revisión"),
                    ("paid", "Pagado"),
                    ("cancelled", "Rechazado"),
                ],
                default="pending",
                max_length=20,
                verbose_name="Estado",
            ),
        ),
    ]
