name: CI (Lint + Tests)

on:
  pull_request:
    branches: [ main ]

jobs:
  django-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        working-directory: backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install black flake8 pytest

      - name: Run flake8 (lint)
        working-directory: backend
        run: flake8 core junta_ut

      - name: Check code formatting with black
        working-directory: backend
        run: black --check .

      - name: Run Django tests with pytest
        working-directory: backend
        env:
          DJANGO_SETTINGS_MODULE: junta_ut.settings.dev
        run: pytest -v
